### ISSUE TITLE
请教一下用法

### ISSUE THREAD

**Issue by wby238** [kanasimi/comic#1]
按照说明的方法做了，除了不知道如何弄comic loader.js，就直接将comic loder.sample.js改名为comic loder.js了，下面是对应的命令及错误信息，请问一下为什么出错了？
```
D:\2017编程\Github\comic-master>node ikanman.js 空战魔导士候补生的教官
get_URL_cache_node.cache: Write cache data to [ikanman\main_3A454149B2D2500411BC
344B15DB58A4.js].
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\2017编程\Github\comic-master\
ikanman\main_3A454149B2D2500411BC344B15DB58A4.js'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
    at eval (eval at load_named (eval at <anonymous> (D:\2017编程\Github\comic-m
aster\node_modules\cejs\_for include\node.loader.js:78:10)), <anonymous>:1975:14
)
    at IncomingMessage.eval (eval at load_named (eval at <anonymous> (D:\2017编
程\Github\comic-master\node_modules\cejs\_for include\node.loader.js:78:10)), <a
nonymous>:1595:15)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

D:\2017编程\Github\comic-master>
```

**Comment by wby238** [comment]
目前發現是隻有ikanman的出問題，其他的還是能用的……
